version: '3'
services:
  api:
    container_name: baseball_api
    build:
      context: .
      dockerfile: Dockerfile_api
    ports:
      - "3308:3308"
    depends_on:
      - service
      - db
  service:
    container_name: vorp_service
    build:
      context: .
      dockerfile: Dockerfile_vorpService
    ports:
      - "10000"
  db:
      container_name: baseball_db
      build:
        context: .
        dockerfile: Dockerfile_db
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=mypass
